version: '3.8'

services:
  # PostgreSQL Database with PostGIS extension
  postgres:
    image: postgis/postgis:15-3.4
    container_name: rgb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_guide_belarus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/02_architecture:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rgb_network

  # Redis Cache and Session Store
  redis:
    image: redis:7-alpine
    container_name: rgb_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - rgb_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  rgb_network:
    driver: bridge


