name: restaurant_guide_mobile
version: 1.0.0+1
description: Мобильное приложение Restaurant Guide Belarus v2.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.4.3
  google_maps_flutter: ^2.5.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
