/* eslint-env jest */
/* eslint comma-dangle: 0 */
/**
 * Refresh Token Rotation Integration Tests
 *
 * Covers the rotation chain against a real database:
 * - the successor is recorded in replaced_by, so a replay can be answered
 * - a replay inside the reuse grace window returns THE SAME successor
 * - a replay outside it, or after logout, still costs every session
 * - two simultaneous refreshes of one token produce exactly one chain
 *
 * Why a window exists at all is in src/config/auth.js. In short: the clients
 * replay a burned token by themselves — the Dio 5xx branch retries
 * /auth/refresh — and without the window every Railway redeploy that lands
 * between the commit and the response logs a SECURITY ALERT and throws a
 * legitimate user out of their account.
 *
 * Each test states the window it needs. .env.test is generated by CI and .env
 * can leak into a local run, so the ambient value is not something to trust.
 */

import request from 'supertest';
import app from '../../server.js';
import { refreshAccessToken } from '../../services/authService.js';
import { clearAllData, query } from '../utils/database.js';
import { createUserAndGetTokens } from '../utils/auth.js';
import { testUsers } from '../fixtures/users.js';

const GRACE_ENV = 'REFRESH_REUSE_GRACE_SECONDS';
const originalGrace = process.env[GRACE_ENV];

const refresh = (refreshToken) =>
  request(app).post('/api/v1/auth/refresh').send({ refreshToken });

const tokenRows = (userId) =>
  query(
    'SELECT id, token, used_at, replaced_by FROM refresh_tokens WHERE user_id = $1 ORDER BY created_at',
    [userId],
  );

beforeEach(async () => {
  await clearAllData();
  process.env[GRACE_ENV] = '60';
});

afterAll(async () => {
  await clearAllData();
  if (originalGrace === undefined) {
    delete process.env[GRACE_ENV];
  } else {
    process.env[GRACE_ENV] = originalGrace;
  }
});

describe('POST /api/v1/auth/refresh — rotation chain', () => {
  test('records the successor in replaced_by', async () => {
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    const response = await refresh(refreshToken).expect(200);

    const { rows } = await tokenRows(user.id);
    const burned = rows.find((row) => row.token === refreshToken);
    const successor = rows.find((row) => row.token === response.body.data.refreshToken);

    expect(rows).toHaveLength(2);
    expect(burned.used_at).not.toBeNull();
    // Without this link a replay has no successor to hand back and the window
    // cannot exist — the column has been in the schema since migration 001 and
    // went unwritten until now.
    expect(burned.replaced_by).toBe(successor.id);
    expect(successor.used_at).toBeNull();
  });
});

describe('POST /api/v1/auth/refresh — reuse grace window', () => {
  test('replay inside the window returns the same successor and no new row', async () => {
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    const first = await refresh(refreshToken).expect(200);
    const replay = await refresh(refreshToken).expect(200);

    // The same successor, not a fresh pair: a second chain would leave two
    // live tokens and make the next replay indistinguishable from theft.
    expect(replay.body.data.refreshToken).toBe(first.body.data.refreshToken);
    expect(replay.body.data.user.id).toBe(user.id);
    expect(replay.body.data.tokenType).toBe('Bearer');

    const { rows } = await tokenRows(user.id);
    expect(rows).toHaveLength(2);
    expect(rows.filter((row) => row.used_at === null)).toHaveLength(1);
  });

  test('replay outside the window revokes every session', async () => {
    process.env[GRACE_ENV] = '30';
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    await refresh(refreshToken).expect(200);

    // Age the rotation rather than sleep through it. The shift happens in SQL
    // because used_at is `timestamp without time zone`: a JS Date would be
    // written in local time and the comparison would drift by the offset.
    await query(
      "UPDATE refresh_tokens SET used_at = NOW() - interval '31 seconds' WHERE token = $1",
      [refreshToken],
    );

    const response = await refresh(refreshToken).expect(403);
    expect(response.body.error.code).toBe('TOKEN_REUSE_DETECTED');

    // Revocation is the whole point of the strict path: the successor the
    // legitimate client is holding dies with the rest.
    const { rows } = await tokenRows(user.id);
    rows.forEach((row) => expect(row.used_at).not.toBeNull());
  });

  // Deliberately not "restores strict one-shot rotation": with the window off a
  // stale replay is theft again, but the caller that loses the atomic claim is
  // still answered from the successor (config/auth.js). The body below covers
  // the stale replay only, and the title says so.
  test('window of 0 refuses a stale replay', async () => {
    process.env[GRACE_ENV] = '0';
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    await refresh(refreshToken).expect(200);

    const response = await refresh(refreshToken).expect(403);
    expect(response.body.error.code).toBe('TOKEN_REUSE_DETECTED');

    const { rows } = await tokenRows(user.id);
    rows.forEach((row) => expect(row.used_at).not.toBeNull());
  });

  test('a used_at in the future is outside the window, not inside it forever', async () => {
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    await refresh(refreshToken).expect(200);

    // used_at is written by NOW() on the rotation path but still by a JS Date
    // on the logout and revoke paths, and a JS Date reaches a `timestamp
    // without time zone` column in the process's local time — three hours ahead
    // under TZ=Europe/Minsk. With only a lower bound such a row would never
    // leave the window.
    await query(
      "UPDATE refresh_tokens SET used_at = NOW() + interval '3 hours' WHERE token = $1",
      [refreshToken],
    );

    const response = await refresh(refreshToken).expect(403);
    expect(response.body.error.code).toBe('TOKEN_REUSE_DETECTED');

    const { rows } = await tokenRows(user.id);
    rows.forEach((row) => expect(row.used_at).not.toBeNull());
  });

  test('a deactivated account is not served from the window', async () => {
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    await refresh(refreshToken).expect(200);
    await query('UPDATE users SET is_active = false WHERE id = $1', [user.id]);

    // Deactivation is how an account is closed or suspended. The window exists
    // to forgive a lost response, and a closed account has nothing to forgive:
    // handing it a fresh access token would keep a suspended user working for
    // another four hours.
    const response = await refresh(refreshToken).expect(403);
    expect(response.body.error.code).toBe('TOKEN_REUSE_DETECTED');
  });

  test('a successor belonging to another user is not handed out', async () => {
    const victim = await createUserAndGetTokens(testUsers.regularUser);
    const stranger = await createUserAndGetTokens(testUsers.regularUser2);

    await refresh(victim.refreshToken).expect(200);

    // The foreign key on replaced_by pins it to a refresh_tokens id and says
    // nothing about whose row that is. The access token is minted from the
    // burned row's user while the refresh token comes from the successor, so an
    // unconstrained join would answer with one user's identity and another
    // user's refresh token.
    const { rows: strangerRows } = await tokenRows(stranger.user.id);
    await query('UPDATE refresh_tokens SET replaced_by = $1 WHERE token = $2', [
      strangerRows[0].id,
      victim.refreshToken,
    ]);

    const response = await refresh(victim.refreshToken).expect(403);
    expect(response.body.error.code).toBe('TOKEN_REUSE_DETECTED');

    // The stranger's session is untouched: neither handed over nor revoked.
    const { rows: after } = await tokenRows(stranger.user.id);
    expect(after[0].used_at).toBeNull();
  });

  test('a token burned by logout is never forgiven, however fresh', async () => {
    const { accessToken, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    await request(app)
      .post('/api/v1/auth/logout')
      .set('Authorization', `Bearer ${accessToken}`)
      .send({ refreshToken })
      .expect(200);

    // Logout burns the row without naming a successor, so there is nothing to
    // replay: after a deliberate exit, a second presentation is suspicious.
    const response = await refresh(refreshToken).expect(403);
    expect(response.body.error.code).toBe('TOKEN_REUSE_DETECTED');
  });
});

describe('POST /api/v1/auth/refresh — concurrent rotation', () => {
  test('two simultaneous refreshes of one token produce exactly one chain', async () => {
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    const [first, second] = await Promise.all([refresh(refreshToken), refresh(refreshToken)]);

    expect(first.status).toBe(200);
    expect(second.status).toBe(200);

    // Both callers walk away with the same successor. Without the atomic claim
    // (`AND used_at IS NULL`) both would pass the used_at check, mint separate
    // successors, and leave two live chains — a fork that is invisible in the
    // response and only surfaces later as a false theft alarm.
    expect(first.body.data.refreshToken).toBe(second.body.data.refreshToken);

    const { rows } = await tokenRows(user.id);
    expect(rows).toHaveLength(2);
    expect(rows.filter((row) => row.used_at === null)).toHaveLength(1);
    expect(rows.find((row) => row.used_at === null).token).toBe(
      first.body.data.refreshToken,
    );
  });

  test('the claim survives a genuine interleave, not just a serialised one', async () => {
    const { user, refreshToken } = await createUserAndGetTokens(testUsers.regularUser);

    // Deliberately below the HTTP layer. Two supertest requests each open their
    // own connection first, which is enough for one to finish the whole
    // rotation before the other starts looking the token up — the outcome is
    // then produced by the replay path and says nothing about the claim.
    // Calling the service directly dispatches both lookups in the same tick,
    // so both requests really do pass the used_at check before either writes,
    // which is the state `AND used_at IS NULL` exists to survive.
    const results = await Promise.all([
      refreshAccessToken(refreshToken),
      refreshAccessToken(refreshToken),
    ]);

    // One chain, one live token, whichever request got there first.
    expect(results[0].refreshToken).toBe(results[1].refreshToken);

    const { rows } = await tokenRows(user.id);
    expect(rows).toHaveLength(2);
    expect(rows.filter((row) => row.used_at === null)).toHaveLength(1);
    expect(rows.find((row) => row.used_at === null).token).toBe(results[0].refreshToken);
  });
});
